import Head from 'next/head'

import Form from '../components/form/Form'
import Info from '../components/info/Info'
import Main from '../components/main/Main'
import Navbar from '../components/navbar/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Landing Food</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <Info />
      <Form />
      
    </div>
  )
}
