import Head from "next/head";
import Form from "../components/Form/Form.js";
import Info from "../components/Info/Info.js";
import Main from "../components/Main/Main.js";
import Menu from "../components/Menu/Menu.js";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Malis Food</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Menu />
      <Main />
      <Info />
      <Form />
    </div>
  );
}
