import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="container">
        <div class="notification is-dark">
          This container is <strong>centered</strong> on desktop and larger
          viewports.
        </div>
      </div>
      <div className="container">

      <div class="columns">
        <div class="column has-background-primary" >First column</div>
        <div class="column">Second column</div>
      </div>
      </div>
    </div>
  );
}
